### ISSUE TITLE
OSS Repository Down?

### ISSUE THREAD

**Issue by ryber** [sonatype/ossindex-public#10]
Hello, this morning all of our projects are throwing this:

org.sonatype.ossindex.service.client.transport.Transport$TransportException: Unexpected response; status: HTTP/1.1 500 Internal Server Error
    at org.sonatype.ossindex.service.client.transport.HttpClientTransport.post (HttpClientTransport.java:101)

**Comment by jdillon** [comment]
Thanks, we are looking into it.

**Comment by jdillon** [comment]
Should be resolved now.

**Comment by ryber** [comment]
Confirmed! Thank you! 💯
