### ISSUE TITLE
SSL Certificate Renewal Request

### ISSUE THREAD

**Issue by marcchanwork** [sonatype/ossindex-public#36]
SSL Certificate expired for URL: https://ossindex.sonatype.org/api/v3/component-report
<img width="507" alt="image" src="https://user-images.githubusercontent.com/103158595/170403232-1d864c80-e35f-4994-8fff-5091d8d96deb.png">

Error occurred in our gradle pipelines:
```
	AnalysisException: Failed to request component-reports
		caused by SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
		caused by ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
		caused by CertPathValidatorException: validity check failed
		caused by CertificateExpiredException: NotAfter: Wed May 25 23:59:59 GMT 2022
```

**Comment by ken-duck** [comment]
Thanks for the heads up. I have informed our OPs team and hope to have this resolved as soon as possible.

Ken Duck
Sonatype

**Comment by marcchanwork** [comment]
Thanks @ken-duck! SSL certs have been renewed:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/103158595/170409907-52094fb4-5e84-4e56-af06-6a268ae50b41.png">
