### ISSUE TITLE
OssIndex 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by mircodariol** [sonatype/ossindex-public#48]
Hi,

OssIndex seems to be down, is someone already looking into the problem? Is there any news?

This error is causing issues with all our dependency check validations done through the Azure DevOps DependencyCheck task.

For more detail, see the following issue:
https://github.com/jeremylong/DependencyCheck/issues/5564

**Comment by pheerathach** [comment]
I'm facing this issue too.

**Comment by robtimus** [comment]
I also reported this through https://issues.sonatype.org/browse/MVNCENTRAL-7940.

**Comment by ton11797** [comment]
I'm encountering an error while validating dependency checks as well.

**Comment by damercier** [comment]
We have the same issue in our validation pipelines (using the [sbt-dependency-check](https://github.com/albuch/sbt-dependency-check) plugin)

**Comment by robtimus** [comment]
https://ossindex.sonatype.org/ is up again.

**Comment by damercier** [comment]
I confirm that this is solved for us ✅

**Comment by joedragons** [comment]
We did have an outage, all shows as resolved now.  Closing this out.
