### ISSUE TITLE
API call : rate limit 

### ISSUE THREAD

**Issue by rmjstn** [sonatype/ossindex-public#49]
Hello,

I want to use the Sonatype OSS Index API. In the documentation it says that there is a limit to the number of requests allowed. This limit is higher in the case of creating an account. How high is this limit (I did not find the information)?

[Extract from the documentation](https://ossindex.sonatype.org/doc/rest) : 
```
Rate and request metric limits apply to requests. If limits are exceeded then responses will indicate 429 Too many requests status. There are a number of request metrics that may trigger the 429 status.
Authenticated requests have a higher limit. Register for an account and authenticate requests to get a higher limit.
```

Thanks,

Rémy

**Comment by anastasia-vanriet** [comment]
Hi Rémy,

Thank you for your interest in OSS Index! Anonymous (without an account) users have a limit of 16 requests, and authenticated (with an account) users have a limit of 64 requests. Once the limit has been reached, every 1 minute the capacity increases by 1 until it reaches the full value. There is a limit of 128 components per HTTP request.

Please let us know if you have any further questions!

Anastasia

**Comment by p3pijn** [comment]
Hi @anastasia-vanriet ,
I was wondering if maybe anything changed recently in the rate limits of the OSSIndex API? We see in the logs of our pipelines that we start hitting rate limits (status code 429) already somewhere between 5 and 7 requests per minute, and this is in authenticated mode. Are the below numbers still accurate?

- 64 requests per minute for authenticated requests
- 16 requests per minute for unauthenticated requests
- After hitting the rate limit: increase rate by 1 request per minute

**Comment by anastasia-vanriet** [comment]
Hi @p3pijn,

I can confirm that you numbers you listed are still accurate.

To enable us to better assist you, we will require some information for troubleshooting purposes. Could you send us the email address(es) and/or IP address(es) with which you are seeing this behavior, as well as the exact message that accompanies the 429 status codes? You can email the information to ossindex@sonatype.org and reference this thread.

Anastasia

**Comment by p3pijn** [comment]
Hi @anastasia-vanriet, many thanks for your response, I have sent an e-mail last week with the requested info.

**Comment by anastasia-vanriet** [comment]
Hi @p3pijn,

Thank you for sending us the data! We'll investigate the issue and get back to you as soon as we can.

**Comment by ken-duck** [comment]
Hi @p3pijin,

Many apologies, but I have been investigating the issue and have been unable to find your email. Perhaps it got caught in spam filters or something. Could you send it to me directly at kduck@sonatype.com ?

Note, I will delete this comment once I receive it so my email doesn't stay out there too long ;)

**Comment by p3pijn** [comment]
@ken-duck I have forwarded the e-mail to you 🙂

**Comment by ken-duck** [comment]
Got it. Thanks!
